spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.93.15:3306/library
    username: root
    password: Loveyou1314520.

# token
token:
  privateKey: 'hello kitty'
  yangToken: 1000000
  oldToken: 3000000000
